language: ruby
rvm:
  - 2.1.3
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"
script: bundle exec rspec spec
